db:
  host: '192.168.0.101'
  port: 3306
  user: 'dev'
  password: 'password'
  name: 'choice'

consumer:
  brokers: ['192.168.0.105:9092']
  topic: 'store.choice.choice'
  group_id: 'consumer-choice-group'

cache:
  address: '192.168.0.105'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1

health:
  address: '192.168.0.101'
  port: ':8050'
  shutdown_endpoint: '/api/v1/consumer_superhero_choice_health/shutdown'
  content_type: 'application/json'

