db:
  host: '192.168.1.229'
  port: 3306
  user: 'dev'
  password: 'Awesome85**'
  name: 'choice'

consumer:
  brokers: ['192.168.1.229:9092']
  topic: 'store.choice.choice'
  group_id: 'consumer.choice.group'

cache:
  address: '192.168.1.229'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  choice_key_format: 'choice.%s.%s'
  likes_key_format: 'likes.for.%s'

health:
  port: ':8050'
  shutdown_endpoint: '/api/v1/consumer_superhero_choice_health/shutdown'
  content_type: 'application/json'

